Translate 'Flutter for RN' - 3
bro-jo/website pull request #63
Opened 2019-05-11 07:18 UTC by bro-jo

2019-05-11 16:07 UTC, BurningDroid requested changes

2019-05-11 16:07 UTC, yoonhok524 commented on src/docs/get-started/flutter-for/react-native-devs.md
> + 앱이 연결된 기기나, iOS 시뮬레이터 혹은 Android 에뮬레이터에서 실행될 것입니다.
보통 애뮬레이터를 더 많이 쓰지 않나요??

2019-05-11 16:07 UTC, yoonhok524 commented on src/docs/get-started/flutter-for/react-native-devs.md
> +Flutter에서는 커스텀 위젯을 만들기 위해 클래스를 정의하면 그 위젯을 재사용 할 수 있습니다.
재사용 할 수 있습니다. -> 재사용할 수 있습니다.

2019-05-11 16:07 UTC, yoonhok524 commented on src/docs/get-started/flutter-for/react-native-devs.md
> +다음 스크린샷은 재사용 할 수 있는 CustomCard 클래스의 예를 보여줍니다.
재사용 할 수 있는 -> 재사용할 수 있는

2019-05-14 05:37 UTC, merged

2019-05-18 08:54 UTC, mcsys commented on src/docs/get-started/flutter-for/react-native-devs.md
> + 앱이 연결된 기기나, iOS 시뮬레이터 혹은 Android 에뮬레이터에서 실행될 것입니다.
명칭이 AS 의 경우는 에뮬레이터로 되어 있고
xcode는 시뮬레이터로 되어 있네요

2019-05-18 09:20 UTC, mcsys commented on src/docs/get-started/flutter-for/react-native-devs.md
> +분리된 함수를 만들면 위젯을 앱 내에서 재사용할 수 있게 됩니다.
함수나 위젯을 분리해서 만드는것은 앱 내에서 컴포넌트를 재사용할 수 있게 해줍니다.