Translate 'Flutter for RN' - 4
bro-jo/website pull request #64
Opened 2019-05-14 08:41 UTC by bro-jo

2019-05-14 08:46 UTC, JUSTIVE commented
>During a build, Flutter places assets into a special archive called the *asset
>bundle*, which apps read from at runtime.
를
>빌드하는 동안 Flutter는 *asset bundle*이라 불리는 특수한 아카이브에 asset을 저장합니다.
>런타임에 앱이 아카이브에서 읽어옵니다.
로 번역하셨는데,

>빌드 중에, Flutter는 런타임 때에 앱이 읽어올 *asset bundle*이라 불리는 특수한 아카이브에 asset을 저장합니다

가 더 자연스럽지 않을까요?

2019-05-15 06:55 UTC, BurningDroid requested changes

2019-05-15 06:55 UTC, yoonhok524 commented on src/docs/get-started/flutter-for/react-native-devs.md
> +각 asset은 `pubspec.yaml`에 명시된 상대 경로에 의해서 asset 파일이 어디에 있는 구분됩니다.
어디에 있는 구분됩니다. -> 어디에 있는지 구분됩니다.

2019-05-15 06:55 UTC, yoonhok524 commented on src/docs/get-started/flutter-for/react-native-devs.md
> +asset이 어떤 순서로 됐는지는 중요하지 않습니다.
"asset이 정의된/선언된 순서는 중요하지 않습니다." 는 어떨까요?

2019-05-18 09:31 UTC, mcsys commented on src/docs/get-started/flutter-for/react-native-devs.md
> +asset이 어떤 순서로 됐는지는 중요하지 않습니다.
이게 좀 더 깔끔한 느낌이네요

2019-05-18 09:34 UTC, mcsys approved these changes

2019-05-19 04:09 UTC, merged