Translate 'Flutter for RN' - 6
bro-jo/website pull request #67
Opened 2019-05-23 14:11 UTC by bro-jo

2019-05-23 14:27 UTC, BurningDroid requested changes

2019-05-23 14:27 UTC, yoonhok524 commented on src/docs/get-started/flutter-for/react-native-devs.md
> +위젯을 가운대 정렬 하기 위해, `Center` 위젯으로 감싼 다음
가운대 -> 가운데

2019-05-23 14:27 UTC, yoonhok524 commented on src/docs/get-started/flutter-for/react-native-devs.md
> +위젯을 사용해서 만듭니다.
험;; 이 부분은 좀체 뭔말인지 이해가 안가네요;;
영문장이 너무 어려워요;;;

2019-05-25 01:18 UTC, merged

2019-05-25 02:51 UTC, calc2te commented on src/docs/get-started/flutter-for/react-native-devs.md
> +위젯을 사용해서 만듭니다.
저도 이 부분이 참 어색하네요.
번역기의 힘을 도와 조금 다듬어봤을때 아래처럼 바꾸면 어떨까 합니다.

Flutter에서 위젯을 사용하여 현재 설정이나 상태에 따라 뷰가 어떻게 보여야 하는지 담겨있는 UI를 만듭니다.

2019-05-25 11:26 UTC, bro-jo commented on src/docs/get-started/flutter-for/react-native-devs.md
> +위젯을 사용해서 만듭니다.
약간 의역해서 아래와 같이 해보았는데 어떤가요??

> Flutter에서는 UI를 만들 때 현재 상태와 설정에 따라 어떻게 보일지에 대한 정보를 담고 있는 위젯을 사용합니다.